/**
 * Common short names / nicknames on bet slips → the full names used by The Odds API and ESPN.
 * Keys and values are compared after normalize() (lowercase, no accents or punctuation).
 */
export const TEAM_ALIASES: Record<string, string> = {
  // England
  "man utd": "manchester united",
  "man united": "manchester united",
  "man u": "manchester united",
  mufc: "manchester united",
  "man city": "manchester city",
  mcfc: "manchester city",
  spurs: "tottenham hotspur",
  tottenham: "tottenham hotspur",
  wolves: "wolverhampton wanderers",
  wolverhampton: "wolverhampton wanderers",
  brighton: "brighton and hove albion",
  "brighton hove albion": "brighton and hove albion",
  forest: "nottingham forest",
  "nottm forest": "nottingham forest",
  "notts forest": "nottingham forest",
  villa: "aston villa",
  newcastle: "newcastle united",
  "west ham": "west ham united",
  leeds: "leeds united",
  "sheff utd": "sheffield united",
  "sheffield utd": "sheffield united",
  "sheff wed": "sheffield wednesday",
  bournemouth: "afc bournemouth",
  palace: "crystal palace",
  ipswich: "ipswich town",
  leicester: "leicester city",
  coventry: "coventry city",
  hull: "hull city",
  "qpr": "queens park rangers",
  "west brom": "west bromwich albion",
  wba: "west bromwich albion",
  // Spain
  barca: "barcelona",
  "fc barcelona": "barcelona",
  atleti: "atletico madrid",
  "atletico de madrid": "atletico madrid",
  "athletic bilbao": "athletic club",
  "real sociedad de futbol": "real sociedad",
  betis: "real betis",
  "celta": "celta vigo",
  // Italy
  inter: "inter milan",
  internazionale: "inter milan",
  "inter milano": "inter milan",
  milan: "ac milan",
  juve: "juventus",
  napoli: "napoli",
  "ssc napoli": "napoli",
  roma: "as roma",
  lazio: "lazio",
  // Germany
  bayern: "bayern munich",
  "bayern munchen": "bayern munich",
  "fc bayern": "bayern munich",
  bvb: "borussia dortmund",
  dortmund: "borussia dortmund",
  gladbach: "borussia monchengladbach",
  "monchengladbach": "borussia monchengladbach",
  leverkusen: "bayer leverkusen",
  leipzig: "rb leipzig",
  frankfurt: "eintracht frankfurt",
  // France
  psg: "paris saint germain",
  "paris sg": "paris saint germain",
  "paris saint-germain": "paris saint germain",
  marseille: "olympique marseille",
  om: "olympique marseille",
  lyon: "olympique lyonnais",
  ol: "olympique lyonnais",
  // Portugal / Netherlands / Scotland
  benfica: "sl benfica",
  sporting: "sporting cp",
  "sporting lisbon": "sporting cp",
  porto: "fc porto",
  ajax: "ajax amsterdam",
  psv: "psv eindhoven",
  feyenoord: "feyenoord",
  celtic: "celtic",
  rangers: "rangers",
};
